### ISSUE TITLE
Display a dialog asking to accept or cancel a takeback

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#135] opened 2021-09-26 19:31 UTC
When a player clicks on the **Propose a takeback** button, their opponent should be displayed a dialog asking to accept or cancel the takeback. 

See https://github.com/chesslablab/chess-server/issues/36

**Comment by Divyateja04** [comment] 2021-09-27 02:42
Okay so I have no idea about php and might end up messing it up so if you can guide me I can work on it

**Comment by programarivm** [comment] 2021-09-27 08:32
Yes, this one involves some programming on the server side as well, but if this is okay let me give you a hint.

For the time being let's just display a dialog to **Accept** or **Cancel** the takeback when the **Propose a takeback** button is clicked.

Happy learning and coding!

**Comment by Divyateja04** [comment] 2021-09-27 09:35
Yeah but I have 0 knowledge about php is the issue here

**Comment by programarivm** [comment] 2021-09-27 10:09
Well, I could work on the server side if that's okay.

No more programming is required to close this issue, it's just display the dialog when the button is clicked.

Thanks!

**Comment by Divyateja04** [comment] 2021-09-27 11:02
Okay, I'll try to display a dialog when the button is clicked, any hint on how I go about doing that?

**Comment by programarivm** [comment] 2021-09-27 13:29
Probably a good first step is to add a new dialog file similarly as with [components/EnterInviteCodeDialog.js](https://github.com/chesslablab/redux-chess/blob/master/src/components/EnterInviteCodeDialog.js).

**Comment by Divyateja04** [comment] 2021-09-27 14:47
Um btw a doubt, why have you added the propse the takeback button inside the paper block?
It looked and feels better below the paper block right?

**Comment by Divyateja04** [comment] 2021-09-27 16:58
Hey, so I added the actiontypes/constants and the reducer file and also edited the rootreducer file, took inspiration from loadFenDialog

The problem is as long as the constants are the following it doesn't load any dialog
```
const requestTakebackDialogActionTypes = {
	CLOSE: 'CLOSE_TAKEBACK_DIALOG',
	OPEN: 'OPEN_TAKEBACK_DIALOG'
};

export default requestTakebackDialogActionTypes;
```
But if they are the following:
```
const requestTakebackDialogActionTypes = {
	CLOSE: 'CLOSE_LOAD_FEN_DIALOG',
	OPEN: 'OPEN_LOAD_FEN_DIALOG'
};

export default requestTakebackDialogActionTypes;
```
it loads the fen dialog


ButtonsPlayFriendMode.js
```
import React from 'react';
import Button from '@material-ui/core/Button';
import { useSelector, useDispatch } from 'react-redux';

import requestTakebackDialogActionTypes from '../constants/requestTakebackDialogActionTypes';

const ButtonsPlayFriendMode = () => {
  const state = useSelector(state => state);
  const dispatch = useDispatch();

  const [anchorElRequestTakeback, setAnchorElRequestTakeback] = React.useState(null);

  const handleCloseRequestTakeback = () => {
    setAnchorElRequestTakeback(null);
  };

  if (!state.mode.playfriend.accepted) { //Remember to remove this comment and ! after
    return (
      <div>
        <Button 
        variant="outlined"
        onClick={() => {
          dispatch({ type: requestTakebackDialogActionTypes.OPEN });
          handleCloseRequestTakeback();
        }}
        >
          Propose a takeback
        </Button>
      </div>
    );
  }

  return null;
}

export default ButtonsPlayFriendMode;
```
this is the requestTakebackDialogReducer.js
```
import requestTakebackDialogActionTypes from '../constants/requestTakebackDialogActionTypes';

const initialState = {
  open: false
};

const reducer = (state = initialState, action) => {
  switch (action.type) {
    case requestTakebackDialogActionTypes.CLOSE:
      return {
        ...state,
        open: false,
      };
    case requestTakebackDialogActionTypes.OPEN:
      return {
        ...state,
        open: true,
      };
    default:
      return state;
  }
};

export default reducer;
```

Any idea why this is happening?

**Comment by Divyateja04** [comment] 2021-09-27 17:20
okay I figured out what was happening, somehow whenever I click the request a takeback button it was going through the loadfen actions, do you have any idea why?
I'm pretty sure the buttonsplayfriendmode doesn't even mention it anywhere

**Comment by Divyateja04** [comment] 2021-09-27 17:37
Hey, I made the dialog with an accept button and a close button
![image](https://user-images.githubusercontent.com/28446977/134957794-46e2b9cb-ecfd-450a-9d7c-c127ef98e030.png)
1. As of now it appears whenever I click the propose button, how do I make it appear on the other opponent's side only?
2. Here's my code for the Dialog:

```
import React from "react";
import { Button, Dialog, DialogActions, DialogContent, DialogTitle, TextField } from '@material-ui/core';
import { useDispatch, useSelector } from "react-redux";
import { makeStyles } from '@material-ui/core/styles';
import { wsMssgStartLoadfen, wsMssgQuit } from '../actions/serverActions';
import requestTakebackDialogActionTypes from '../constants/requestTakebackDialogActionTypes';

const useStyles = makeStyles((theme) => ({
  root: {
    '& .MuiTextField-root': {
      margin: theme.spacing(1),
    },
  },
}));

const RequestTakebackDialog = () => {
  const state = useSelector(state => state);
  const dispatch = useDispatch();
  const classes = useStyles();

  const handleTakeback = (event) => {
    event.preventDefault();
    wsMssgQuit(state).then(() => {
      wsMssgStartLoadfen(state, event.target.elements.takeback.value).then(() => {
        dispatch({ type: requestTakebackDialogActionTypes.CLOSE });
      });
    });
  }

  return (
    <Dialog open={state.requestTakebackDialog.open} maxWidth="sm" fullWidth={true}>
      <DialogTitle>The opponent Proposed a Takeback</DialogTitle>
      <DialogContent>
        <form className={classes.root} onSubmit={handleTakeback}>
          <DialogActions>
            <Button type="submit">
              Accept
            </Button>
            <Button onClick={() => dispatch({ type: requestTakebackDialogActionTypes.CLOSE })}>
              Cancel
            </Button>
          </DialogActions>
        </form>
      </DialogContent>
    </Dialog>
  );
}

export default RequestTakebackDialog;
```

**Comment by programarivm** [comment] 2021-09-27 18:07
The dialog looks good! Let's review it within the next few days. Some programming needs to be done on the server side, and most probably a new action has to be added in [`actions/serverActions.js`](https://github.com/chesslablab/redux-chess/blob/master/src/actions/serverActions.js) accordingly.

The takeback button inside the paper block seemed the simplest possible way to add the button since there's no CSS-in-JS code involved.

**Comment by Divyateja04** [comment] 2021-09-28 02:43
Sure

**Comment by programarivm** [comment] 2021-09-28 15:55
Thanks, https://github.com/chesslablab/php-chess/issues/55 has been closed and I'll try to implement https://github.com/chesslablab/chess-server/issues/36 asap.

**Comment by programarivm** [comment] 2021-09-29 15:48
@Divyateja04 the issues https://github.com/chesslablab/php-chess/issues/55 and https://github.com/chesslablab/chess-server/issues/36 have been closed.

Described below are the sequence of commands that would allow Bob to propose a takeback to Alice after playing `1.e4 e5`.

Alice:

```
$ websocat ws://localhost:8080
/start playfriend w 10
{"\/start":{"mode":"playfriend","jwt":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwY2hlc3MubmV0IiwiaWF0IjoxNjMyOTI4OTY4LCJjb2xvciI6InciLCJtaW4iOiIxMCIsImV4cCI6MTYzMjkyOTU2OH0.KAlahRGFjyg2NF7o7xlh4nV4HrcFng9JhM65IeiPPOQ","hash":"b9bef730966d51284303d9054d33fabb"}}
{"\/accept":{"jwt":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwY2hlc3MubmV0IiwiaWF0IjoxNjMyOTI4OTY4LCJjb2xvciI6InciLCJtaW4iOiIxMCIsImV4cCI6MTYzMjkyOTU2OH0.KAlahRGFjyg2NF7o7xlh4nV4HrcFng9JhM65IeiPPOQ","hash":"b9bef730966d51284303d9054d33fabb"}}
/playfen "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b"
{"\/playfen":{"turn":"w","legal":true,"check":false,"mate":false,"movetext":"1.e4","fen":"rnbqkbnr\/pppppppp\/8\/8\/4P3\/8\/PPPP1PPP\/RNBQKBNR b KQkq e3"}}
{"\/playfen":{"turn":"b","legal":true,"check":false,"mate":false,"movetext":"1.e4 e5","fen":"rnbqkbnr\/pppp1ppp\/8\/4p3\/4P3\/8\/PPPP1PPP\/RNBQKBNR w KQkq e6"}}
{"\/takeback":"propose"}
/takeback accept
{"\/takeback":"accept"}
```

Bob:

```
$ websocat ws://localhost:8080
/accept b9bef730966d51284303d9054d33fabb
{"\/accept":{"jwt":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwY2hlc3MubmV0IiwiaWF0IjoxNjMyOTI4OTY4LCJjb2xvciI6InciLCJtaW4iOiIxMCIsImV4cCI6MTYzMjkyOTU2OH0.KAlahRGFjyg2NF7o7xlh4nV4HrcFng9JhM65IeiPPOQ","hash":"b9bef730966d51284303d9054d33fabb"}}
{"\/playfen":{"turn":"w","legal":true,"check":false,"mate":false,"movetext":"1.e4","fen":"rnbqkbnr\/pppppppp\/8\/8\/4P3\/8\/PPPP1PPP\/RNBQKBNR b KQkq e3"}}
/playfen "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w"
{"\/playfen":{"turn":"b","legal":true,"check":false,"mate":false,"movetext":"1.e4 e5","fen":"rnbqkbnr\/pppp1ppp\/8\/4p3\/4P3\/8\/PPPP1PPP\/RNBQKBNR w KQkq e6"}}
/takeback propose
{"\/takeback":"propose"}
{"\/takeback":"accept"}
/undomove
{"\/undomove":true}

```

Please let me know if this makes sense.

Happy coding and learning!

**Comment by Divyateja04** [comment] 2021-09-29 16:23
Basically the command to send request is /takeback and for it to be accepted ig its /undomove 
But honestly idk how to work on this part, any help though?

**Comment by programarivm** [comment] 2021-09-29 16:37
That's okay, then you may want to send a PR displaying the dialog.

The following question could be answered in a different issue while programming the dialog:

- As of now it appears whenever I click the propose button, how do I make it appear on the other opponent's side only?

**Comment by Divyateja04** [comment] 2021-09-30 11:28
Yeah sure, but maybe can I send it tonight or tom morning, my laptop has a small issue and I'm trying to fix it out

**Comment by Divyateja04** [comment] 2021-10-01 01:14
Sent the PR

**Comment by Divyateja04** [comment] 2021-10-01 14:40
Hey um, close this too

**Comment by programarivm** [comment] 2021-10-01 14:41
Merged PR https://github.com/chesslablab/redux-chess/pull/138

**Closed** 2021-10-01 14:42 UTC
